# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\john\PycharmProjects\PyBooklet\PyBooklet\resources\PyBooklet.ui'
#
# Created: Sun Feb 12 07:43:31 2012
#      by: pyside-uic 0.2.13 running on PySide 1.0.9
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(349, 578)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(349, 593))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/images/PyBooklet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(349, 531))
        self.centralwidget.setMaximumSize(QtCore.QSize(349, 531))
        self.centralwidget.setObjectName("centralwidget")
        self.generate = QtGui.QPushButton(self.centralwidget)
        self.generate.setEnabled(True)
        self.generate.setGeometry(QtCore.QRect(20, 380, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.generate.setFont(font)
        self.generate.setDefault(False)
        self.generate.setObjectName("generate")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 160, 313, 132))
        self.groupBox.setObjectName("groupBox")
        self.page_size = QtGui.QComboBox(self.groupBox)
        self.page_size.setGeometry(QtCore.QRect(120, 37, 81, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.page_size.setFont(font)
        self.page_size.setObjectName("page_size")
        self.page_size.addItem("")
        self.page_size.addItem("")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 61, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pps = QtGui.QComboBox(self.groupBox)
        self.pps.setGeometry(QtCore.QRect(120, 68, 81, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pps.setFont(font)
        self.pps.setObjectName("pps")
        self.pps.addItem("")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 107, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(120, 100, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setText("")
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 107, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 480, 311, 16))
        self.progressBar.setAutoFillBackground(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.selected_file = QtGui.QLineEdit(self.centralwidget)
        self.selected_file.setGeometry(QtCore.QRect(20, 109, 282, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selected_file.setFont(font)
        self.selected_file.setText("")
        self.selected_file.setObjectName("selected_file")
        self.select_file = QtGui.QPushButton(self.centralwidget)
        self.select_file.setGeometry(QtCore.QRect(297, 109, 37, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.select_file.setFont(font)
        self.select_file.setStatusTip("")
        self.select_file.setWhatsThis("")
        self.select_file.setAccessibleName("")
        self.select_file.setStyleSheet("")
        self.select_file.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/images/dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select_file.setIcon(icon1)
        self.select_file.setIconSize(QtCore.QSize(20, 20))
        self.select_file.setCheckable(False)
        self.select_file.setDefault(False)
        self.select_file.setFlat(False)
        self.select_file.setObjectName("select_file")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(21, 86, 107, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.progressBar_label = QtGui.QLabel(self.centralwidget)
        self.progressBar_label.setGeometry(QtCore.QRect(20, 460, 309, 16))
        self.progressBar_label.setObjectName("progressBar_label")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(22, 309, 121, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.selected_directory = QtGui.QLineEdit(self.centralwidget)
        self.selected_directory.setGeometry(QtCore.QRect(20, 330, 285, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selected_directory.setFont(font)
        self.selected_directory.setObjectName("selected_directory")
        self.select_directory = QtGui.QPushButton(self.centralwidget)
        self.select_directory.setGeometry(QtCore.QRect(297, 330, 37, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_directory.sizePolicy().hasHeightForWidth())
        self.select_directory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.select_directory.setFont(font)
        self.select_directory.setText("")
        self.select_directory.setIcon(icon1)
        self.select_directory.setIconSize(QtCore.QSize(31, 27))
        self.select_directory.setDefault(False)
        self.select_directory.setFlat(False)
        self.select_directory.setObjectName("select_directory")
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, -1, 349, 73))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(33, 33, 33,245);\n"
"border-color: rgba(255, 255, 255, 0);")
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(251, 31, 92, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255,220);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(252, 48, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255,220);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_8.setObjectName("label_8")
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(250, 1, 38, 29))
        self.frame_3.setStyleSheet("background-image: url(:/resources/images/PyBookleticon.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 349, 26))
        self.menubar.setStyleSheet("background-color: rgb(33, 33, 33,245);\n"
"gridline-color: rgba(255, 255, 255, 0);\n"
"selection-background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255,200);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"border-width:0px")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBooklet_Help = QtGui.QAction(MainWindow)
        self.actionBooklet_Help.setEnabled(False)
        self.actionBooklet_Help.setObjectName("actionBooklet_Help")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCheck_For_Updates = QtGui.QAction(MainWindow)
        self.actionCheck_For_Updates.setObjectName("actionCheck_For_Updates")
        self.actionDonate = QtGui.QAction(MainWindow)
        self.actionDonate.setObjectName("actionDonate")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionBooklet_Help)
        self.menuHelp.addAction(self.actionCheck_For_Updates)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionDonate)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.label.setBuddy(self.page_size)
        self.label_2.setBuddy(self.pps)
        self.label_6.setBuddy(self.checkBox)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.selected_file, self.select_file)
        MainWindow.setTabOrder(self.select_file, self.page_size)
        MainWindow.setTabOrder(self.page_size, self.pps)
        MainWindow.setTabOrder(self.pps, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.selected_directory)
        MainWindow.setTabOrder(self.selected_directory, self.select_directory)
        MainWindow.setTabOrder(self.select_directory, self.generate)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PyBooklet", None, QtGui.QApplication.UnicodeUTF8))
        self.generate.setText(QtGui.QApplication.translate("MainWindow", "Generate PDFs", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.page_size.setItemText(0, QtGui.QApplication.translate("MainWindow", "A4", None, QtGui.QApplication.UnicodeUTF8))
        self.page_size.setItemText(1, QtGui.QApplication.translate("MainWindow", "Letter", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Page size", None, QtGui.QApplication.UnicodeUTF8))
        self.pps.setItemText(0, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Pages / Sheet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Double-sided", None, QtGui.QApplication.UnicodeUTF8))
        self.select_file.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">select the PDF file</p></body></html>", "select the PDF file", QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Input File :", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar_label.setText(QtGui.QApplication.translate("MainWindow", "Ready", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Output Folder :", None, QtGui.QApplication.UnicodeUTF8))
        self.select_directory.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">select the output folder</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "PyBooklet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "for PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBooklet_Help.setText(QtGui.QApplication.translate("MainWindow", "Booklet Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheck_For_Updates.setText(QtGui.QApplication.translate("MainWindow", "Check For Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDonate.setText(QtGui.QApplication.translate("MainWindow", "Donate", None, QtGui.QApplication.UnicodeUTF8))

import form_rc
